[project]
name = "league-analysis"
version = "0.1.0"
description = "Web app for comprehensive analysis of League of Legends players, matches and more."
authors = [{ name = "Matěj Kadlec", email = "mat.kadlec@email.cz" }]
dependencies = [
    "apscheduler>=3.11.2",
    "asyncpg>=0.31.0",
    "email-validator>=2.3.0",
    "fastapi>=0.128.8",
    "httpx>=0.28.1",
    "passlib[argon2]>=1.7.4",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "pyjwt[crypto]>=2.10.1",
    "python-Levenshtein>=0.27.3",
    "python-multipart>=0.0.22",
    "slowapi>=0.1.9",
    "sqlalchemy>=2.0.46",
    "structlog>=25.5.0",
    "uvicorn[standard]>=0.40.0",
]
requires-python = ">=3.14.2,<3.15"
license = { text = "All Rights Reserved" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.pyright]
pythonVersion = "3.14"
typeCheckingMode = "standard"
include = ["app"]
exclude = ["**/__pycache__", "**/.pytest_cache", "**/tests", ".venv"]
reportMissingImports = true
reportMissingTypeStubs = "none"

[tool.pytest.ini_options]
addopts = ["--strict-config", "--strict-markers", "-ra"]
asyncio_mode = "auto"
filterwarnings = [
    "error",
    "ignore:'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning:slowapi.extension",
]
testpaths = ["tests"]

[tool.ruff]
target-version = "py314"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "pip-audit>=2.9.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pyright>=1.1.408",
    "ruff==0.16.1",
]
